services:
  - type: web
    name: ai-internship-dashboard
    runtime: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /?health=check
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: HUGGING_FACE_API_KEY
        sync: false
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: "false"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"